### ISSUE TITLE
Cannot get out of sleep?

### ISSUE THREAD

**Issue by SimonFili** [antonialoytorrens/TF101-linux-images#3]
Looks like if I get to "sleep" / black screen, I cannot go out of it.  The only thing that worked was to the long press the power button.

**Comment by antonialoytorrens** [comment]
I also experienced that with my tablet, so this issue is reproducible.
However, I don't have much expertise in this stuff, so I cannot help you very much.
The only workaround is deleting the desktop environment (in this case, the tablet _can_ get out of sleep) or disabling sleep mode under xfce (I haven't tested the second option, see [here](https://www.linuxquestions.org/questions/linux-desktop-74/disable-sleep-mode-under-xfce-870328/)).

```
# xset s off
# xset dpms 0 0 0
# xset -dpms s off
```
