### ISSUE TITLE
Touchscreen rotation

### ISSUE THREAD

**Issue by LongnoseRob** [antonialoytorrens/TF101-linux-images#8]
Mostly I am using my TF101 with the dock, 
but sometimes I would like to use my Tablet again for reading longer documents in portrait orientation.

So I tried using the screen rotation, with the result, that the screen display can be rotated correctly.
but the touchcreen input is not rotated at all.

I found a manual way to do this, based on <script src="https://gist.github.com/mildmojo/48e9025070a2ba40795c.js"></script>
[rotate_desktop.txt](https://github.com/antonialoytorrens/TF101-linux-images/files/7225255/rotate_desktop.txt)

now it would be nice if we could get this automated, either by suning this script or something based on the mate screen rotation widget.
Ideally this would work with the accerlometer, but I have no idea how to get this working

**Comment by antonialoytorrens** [comment]
Thank you @LongnoseRob for the issue! I'll have a deeper look when I have some spare time :)

Off-topic: Anyways, if you are registered on matrix.org, I suggest you to join `#postmarketOS-on-transformers:matrix.org`. We deal with all kinds of issues about Asus Transformer and Tegra chips in general. We don't have many TF101 and perhaps your issue would be addressed quicker :)

**Comment by LongnoseRob** [comment]
Thanks for the feedback.

The mate screen rotation widget does in the end also only calls to xrandr, but does not care about the touchscreen (yet).

OT:
I'll have a look at matrix, some more easy communication with the PM TF101 "team" would be appreciated.

**Comment by antonialoytorrens** [comment]
I have built a working workaround for now:

- In _Caja_ (The MATE file manager): Please go to _Edit -> Preferences_. Then go to _Behavior_ column and enable _single-click to open items_.

- Then, I have attached a [zip file](https://github.com/antonialoytorrens/TF101-linux-images/files/7247909/rotate-screen.zip) with a tweaked version of your script (with comments) and a `.desktop` file.

  - 1. The script:
  `sudo cp /path/of/script/rotate-screen.sh /usr/bin/rotate-screen.sh` (you can place it in `/home/your_username/.local/bin/rotate-screen.sh` if you want too, please create directories if they don't exist yet and modify Exec line in desktop file accordingly).
  **Note**: You may also need to execute `sudo chmod +x /usr/bin/rotate-screen.sh` to fix the file permission error.

  - 2. The .desktop file:
  `sudo cp /path/of/file/rotate-screen.desktop /usr/share/applications/rotate-screen.desktop` (you can place it in `/home/your_username/.local/share/applications/rotate-screen.desktop` if you want too, please create directories if they don't exist yet).

- Now, we need a symlink of the desktop file, so it can be accessible to Desktop:

    - If you have created your desktop file in /usr/share/applications/rotate-screen.desktop:
    `ln -s /usr/share/applications/rotate-screen.desktop /home/your_username/Desktop/rotate-screen.desktop`

    - If you have created your desktop file in /home/your_username/.local/share/applications/rotate-screen.desktop:
    `ln -s /home/your_username/.local/share/applications/rotate-screen.desktop /home/your_username/Desktop/rotate-screen.desktop`

- After that, we can left-click the symlinked desktop file that will appear on the Desktop and select _Properties_. Then, we go to the _Permissions_ column and we tick _Allow executing file as program_.

Now everytime you want to rotate the screen, you are just only a one-click away!


Hope this workaround helps a little bit to deal with your issue. Also, note that this is considered not solved at all because we need a solution that works out of the box without bash scripts.

**Comment by LongnoseRob** [comment]
Thanks for the efforts, I'll give it a try
